---
execute: 
  cache: false
format: 
  pdf:
    include-in-header: 
       text: |
         \newcommand{\textasciicaret}{\^{}}
         \usepackage{fvextra}
         \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
    include-before-body:
        text: |
         \RecustomVerbatimEnvironment{verbatim}{Verbatim}{showspaces = false, showtabs = false, breaksymbolleft={}, breaklines}
---

# Class 3

Plan for today:
- Review how to write functions in Python
- Discuss analyzing pandas DataFrames

In [24]:
import YData_baseball

YData_baseball.download_data("Lahman_2024u/Batting.csv")
YData_baseball.download_data("Lahman_2024u/People.csv")

The file `Batting.csv` already exists.
If you would like to download a new copy of the file, please rename the existing copy of the file.
The file `People.csv` already exists.
If you would like to download a new copy of the file, please rename the existing copy of the file.

In [25]:
import pandas as pd
import numpy as np

## 1. Writing functions

Functions are useful when writing code one wants to reuse. We can create functions in Python using a "def" statement. Let's try it now!

### 1.1 Writing a function to the ERA

Last class we used numpy arrays to calculate a pitcher's ERA from the number of innings pitched and the number of earned runs they gave up using the formula: $$ERA = \frac{earned\_runs}{innings\_pitched} \times 9$$. Let's now turn this code into a function that calculates ERA for us!

The function we will write is called `get_ERA(innings_pitched, earned_runs)` and takes the following arguments: 

1. `innings_pitched`: A sequence showing how many inning a pitcher pitched each year
2. `earned_runs`: A sequence showning how many earned runs a pitcher gave up each year

The function should return two values (as a tuple): 
1. The ERA for each season as a numpy array
2. The total ERA based on all the data as a number

In [26]:
import numpy as np


# Answer

def calc_ERA(innings_pitched, earned_runs):

    # calculate ERA for each season  
    
    earned_runs_array = np.array(earned_runs)  # convert to arrays
    innings_pitched_array = np.array(innings_pitched)
    
    season_ERA = (earned_runs_array / innings_pitched_array) * 9  # calculate ERA
    season_ERA = np.round(season_ERA, 2)

    
    # calculate the total ERA
    total_ERA = np.sum(earned_runs_array)/np.sum(innings_pitched_array) * 9

    return (season_ERA, float(total_ERA))




# Try out the function

# Lists showing Ohtani's seasons, earned runs, and innings pitched
seasons = [2018, 2020, 2021, 2022, 2023, 2025]
earned_runs = [19, 7, 46, 43, 46, 15]
innings_pitched = [51.667, 1.667, 130.333, 166.0, 132.0, 47.0]


# Use tuple unpacking to get ERA for each season and overall ERA
Ohtani_season_ERA, Ohtani_overall_ERA = calc_ERA(innings_pitched, earned_runs)


print(Ohtani_season_ERA)
print(Ohtani_overall_ERA)

[ 3.31 37.79  3.18  2.33  3.14  2.87]
2.9962150086916712

# 2. Pandas DataFrames

Pandas DataFrames are a data structure that allows you to store tabular data in Python. DataFrames are similar to spreadsheets, where each column can have a different type of data (e.g., integers, floats, strings). You can think of a DataFrame as a collection of pandas Series that share the same index. 

Let's explore pandas DataFrames by looking at the [Lahman Database](https://sabr.org/lahman-database/) which contains season level statistics on teams and baseball players (among other things).

### 2.1 Loading batting data

The file called `Batting.csv` contains batting statistics for all players from 1871 to 2024. We can load this data into Python as a pandas DataFrame into the name `batting` using the code below. The code also displays the first 5 rows of the DataFrame using the `.head()` method.

In [27]:
# Do not change this cell, just run it
import pandas as pd

# Load in the dataset from the class GitHub repository
batting = pd.read_csv('Batting.csv')  

batting.head(5)

,playerID,yearID,stint,teamID,lgID,G,G_batting,AB,R,H,...,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,G_old
0,aardsda01,2004,1,SFN,NL,11,NaN,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1,aardsda01,2006,1,CHN,NL,45,NaN,2,0,0,...,0.0,0.0,0,0.0,0.0,0.0,1.0,0.0,0.0,NaN
2,aardsda01,2007,1,CHA,AL,25,NaN,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,aardsda01,2008,1,BOS,AL,47,NaN,1,0,0,...,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN
4,aardsda01,2009,1,SEA,AL,73,NaN,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

**Question 2.1.** What does each row in the data represent and what do the columns represent? Also, how many rows and columns are there in the batting table?  

Hint: using the `.shape` property can be useful here.


**Answers:**

- Each row represents: an individual baseball player in a given season
- Each column represents: different information/statistics about a given baseball player in a given season
- There are 126,907 rows in the table and 24 columns in the table

In [28]:
print(batting.shape)

(126907, 24)

### 2.2 Selecting a subset of columns from a DataFrame

We can select a subset of columns using the syntax: `my_df[["col1", "col2"]]`. 

**Question 2.2** Select the columns `playerID`, `yearID`, and `HR` from the batting table. Also, write down a reason why it might be useful to select a subset of columns in the answer section below.

**Answer:** The code below selects the requested columns. The reason that it is useful to select a subset of columns is because it can make it easier to see the information is relevant when only the relevant columns are available and it can also save computer memory.

In [29]:
batting[['playerID', 'yearID','HR']]

         playerID  yearID  HR
0       aardsda01    2004   0
1       aardsda01    2006   0
2       aardsda01    2007   0
3       aardsda01    2008   0
4       aardsda01    2009   0
...           ...     ...  ..
126902  zwilldu01    1915  13
126903  zwilldu01    1916   1
126904   zychto01    2015   0
126905   zychto01    2016   0
126906   zychto01    2017   0

[126907 rows x 3 columns]

### 2.3 Selecting a column as a pandas Series

We can also select a single column from a DataFrame as a pandas Series using the syntax: `my_df["col_name"]`. This is useful when we want to perform operations on a single column of data (e.g., operations that are similar to the operations we can perform on numpy arrays).

In [30]:

HRs = batting["HR"]
Gs = batting["G"]

HR_per_game = HRs / Gs

HR_per_game[0:5]

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
dtype: float64

### 2.4 Using methods on columns in a DataFrame

The pandas Series and DataFrames also have methods that can operate on the values in a column. For example, we can sum the values in a column using the `my_df.sum()` method. We can also use numpy functions on columns of a DataFrame if we extract the data in the columns as pandas Series. For we can also sum the values in a column of a pandas DataFrame using `np.sum(my_df["col_name"]`. 

**Question 4.4**. What is the total number of home runs that have been hit from 1871 through the 2024 season? Please calculate this value using both the pandas `.sum()` method and the numpy `np.sum()` function. 

**Answer:** There have been 340,060 home runs hit from 1871 through 2024

In [31]:
import numpy as np

# Using the pandas .sum() method
print(batting['HR'].sum())


# Using numpy np.sum()
np.sum(batting["HR"])

340060

np.int64(340060)

### 2.5 Selecting a subset of rows from a DataFrame

There are several ways to select rows from a pandas DataFrame. One way is by the rows absolute position in the DataFrame. To select rows by their position in the DataFrame, we can use the `iloc` method. For example, we can select rows 2, 5, and 6 using the syntax: `my_df.iloc[[2,5,6]]`.

We can also select rows based on Index values using `.loc`. For example, if we set the Index to the playerIDs using `batting2 = batting.set_index("playerID")`, we can then get a subset of rows based on the Index values. For example, we could get Hank Aaron's data using: `batting2.loc["aaronha01"]`.  


**Question 2.5:** Select the columns games, home runs, and stolen bases, and the rows 65470, 77657, 74271, and 88498 from the batting table. See if you can do this with **a single line of Python code**! Is there anything similar about these players' statistics?  

**Answer**: These players all have had seasons with 40 home runs and 40 stolen bases!

In [32]:
# Select games from rows 391, 84432, 97140, 10716

batting[['playerID', 'yearID','HR', 'SB']].iloc[[391, 84432, 97140, 107163]]


# this is how I found the players who had over 40 home runs and 40 stolen bases in a season
#batting.query("HR > 40 & SB > 40")

         playerID  yearID  HR    SB
391     acunaro01    2023  41  73.0
84432   ohtansh01    2024  54  59.0
97140   rodrial01    1998  42  46.0
107163  soriaal01    2006  46  41.0

In [33]:
# Also try out setting the Index to the playerID, and then getting Hank Aaron's data (playerID aaronha01)

batting2 = batting.set_index("playerID")
batting2.head(10)

batting2.loc["aaronha01"].head()

,yearID,stint,teamID,lgID,G,G_batting,AB,R,H,2B,...,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,G_old
playerID,,,,,,,,,,,,,,,,,,,,,
aaronha01,1954,1,ML1,NL,122,NaN,468,58,131,27,...,2.0,2.0,28,39.0,NaN,3.0,6.0,4.0,13.0,NaN
aaronha01,1955,1,ML1,NL,153,NaN,602,105,189,37,...,3.0,1.0,49,61.0,5.0,3.0,7.0,4.0,20.0,NaN
aaronha01,1956,1,ML1,NL,153,NaN,609,106,200,34,...,2.0,4.0,37,54.0,6.0,2.0,5.0,7.0,21.0,NaN
aaronha01,1957,1,ML1,NL,151,NaN,615,118,198,27,...,1.0,1.0,57,58.0,15.0,0.0,0.0,3.0,13.0,NaN
aaronha01,1958,1,ML1,NL,153,NaN,601,109,196,34,...,4.0,1.0,59,49.0,16.0,1.0,0.0,3.0,21.0,NaN

### 2.6 Sorting rows of a DataFrame based on values in a column 

We can also sort values in a table using the `my_df.sort_values('col_name')` method. If we want to sort the columns from largest value to the smallest value we can set the additional argument `ascending = False` (i.e., `my_df.sort_values('col_name', ascending = False)`. 


**Question 2.6**. Use the sort function to find the player who has hit the most triples in a season. Can you figure out who this player is? 


**Answer**:  The player is [Chief Wilson](https://en.wikipedia.org/wiki/Chief_Wilson)

In [34]:
batting.sort_values('3B', ascending = False).head(1)

,playerID,yearID,stint,teamID,lgID,G,G_batting,AB,R,H,...,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,G_old
123469,wilsoch01,1912,1,PIT,NL,152,NaN,583,80,175,...,16.0,NaN,35,67.0,NaN,2.0,23.0,NaN,NaN,NaN

### 2.7 Boolean indexing and the .query() methods

As we discussed extensively in YData, you can use Boolean indexing and/or the `.query()` method to extract a DataFrame that only contains rows that meet particular conditions. For example, if we have a DataFrame called `my_df` that has a column called `vals` that has quantitative data, you could extract a DataFrame that only has rows where `vals` are greater than 10 using either:

- `my_df[my_df["vals"] > 10]`
- `my_df.query("vals > 10")`


**Question 2.7** Create DataFrame that only has information for batters/season where the hitters hit 60 or more home runs in a season.

In [35]:

# Using Boolean indexing
display(batting[batting["HR"] >= 60][["playerID",	"yearID", "teamID", "HR"]])


# Using the query method
batting.query("HR >= 60")[["playerID",	"yearID", "teamID", "HR"]]

         playerID  yearID teamID  HR
10441   bondsba01    2001    SFN  73
58722   judgeaa01    2022    NYA  62
70571   marisro01    1961    NYA  61
74513   mcgwima01    1998    SLN  70
74514   mcgwima01    1999    SLN  65
99502    ruthba01    1927    NYA  60
107288   sosasa01    1998    CHN  66
107289   sosasa01    1999    CHN  63
107291   sosasa01    2001    CHN  64

         playerID  yearID teamID  HR
10441   bondsba01    2001    SFN  73
58722   judgeaa01    2022    NYA  62
70571   marisro01    1961    NYA  61
74513   mcgwima01    1998    SLN  70
74514   mcgwima01    1999    SLN  65
99502    ruthba01    1927    NYA  60
107288   sosasa01    1998    CHN  66
107289   sosasa01    1999    CHN  63
107291   sosasa01    2001    CHN  64

### 2.8 Adding and renaming columns

We can add new columns to a DataFrame using the syntax `my_df["new_col_name"] = values`. The values can be a list, a numpy array, or a pandas Series which must be the same length as the DataFrame. 

We can also rename columns using the `.rename()` method. For example, we can rename the column "old_col_name" to "new_col_name" using the syntax `my_df.rename(columns = {"old_col_name": "new_col_name"})`.

**Question 2.8**. Create a new DataFrame called `batting2` that has all the same columns as the `batting` DataFrame but also has a new column in the batting DataFrame called "HR_per_game" that is the number of home runs hit divided by the number of games played. Then, rename the column "HR_per_game" to "HR/G".

In [36]:

# Make a copy of the DataFrame first, otherwise it will modify the original batting DataFrame...
batting2 = batting.copy()


# Answer

batting2["HR_per_game"] = batting2["HR"] / batting2["G"]

batting2 = batting2.rename(columns = {"HR_per_game": "HR/G"})

batting2

,playerID,yearID,stint,teamID,lgID,G,G_batting,AB,R,H,...,CS,BB,SO,IBB,HBP,SH,SF,GIDP,G_old,HR/G
0,aardsda01,2004,1,SFN,NL,11,NaN,0,0,0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000
1,aardsda01,2006,1,CHN,NL,45,NaN,2,0,0,...,0.0,0,0.0,0.0,0.0,1.0,0.0,0.0,NaN,0.000000
2,aardsda01,2007,1,CHA,AL,25,NaN,0,0,0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000
3,aardsda01,2008,1,BOS,AL,47,NaN,1,0,0,...,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000
4,aardsda01,2009,1,SEA,AL,73,NaN,0,0,0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126902,zwilldu01,1915,1,CHF,FL,150,NaN,548,65,157,...,NaN,67,65.0,NaN,2.0,18.0,NaN,NaN,NaN,0.086667
126903,zwilldu01,1916,1,CHN,NL,35,NaN,53,4,6,...,NaN,4,6.0,NaN,0.0,2.0,NaN,NaN,NaN,0.028571
126904,zychto01,2015,1,SEA,AL,13,NaN,0,0,0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000
126905,zychto01,2016,1,SEA,AL,12,NaN,0,0,0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000
126906,zychto01,2017,1,SEA,AL,45,NaN,0,0,0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000

### 2.9 Aggregate statistics by group

We can use the pandas `groupby()` and `.agg()` method to calculate aggregate statistics separately for different groups. For example, we can had a DataFrame called `my_df` that had a categorical column called "group_col" and a quantitative column called "quant_col", we could calculate the sum of the values in the "quant_col" separately for each unique value in the "group_col" using `my_df.groupby("group_col").agg(sum_vals = ("quant_col", "sum"))`

**Question 2.9** Please calculate how many games in total each major league baseball team played. Also, sort the values such that the team that has the most values is at the top of this aggregated DataFrame.

In [37]:

batting.groupby("teamID").agg(total_games = ("G", "sum")).sort_values("total_games", ascending = False)

        total_games
teamID
CHN          270894
PHI          264872
PIT          260370
SLN          258116
CIN          258007
...             ...
BL4              54
AB               45
NWB              41
OKM              36
PFG               9

[255 rows x 1 columns]

### 2.10 Joining/merging DataFrames

We can combine DataFrames together using the `.join()` and `.merge()` methods. The `join()` method joins to DataFrames based on the Index values, while the `.merge()` method joins two DataFrames based on values in columns in the two DataFrames. If we have two DataFrames called `df1` and `df2` that have the same Index values, we can join the using `df1.join(df2)`. Likewise, if the two DataFrame have columns with similar values (but difference Indexes) we can join them using `df1.merge(df2, left_on = "col_df1", right_on = "col_df2)`. We can also use the `how` argument to do, left, right, inner and full joins. 

**Question 2.10** The code below loads information about Major League Baseball player's into a DataFrame called `players`. Please join/merge this DataFrame with the `batting` DataFrame in such a way that all the rows in the `batting` DataFrame are preserved and the corresponding columns in the `players` DataFrame are joined on. Save the results of this joined DataFrame to the name `batting2` and print out the first 5 rows of `batting2`. 

Hint: The `playerID` column, which gives a unique for each baseball player, will be useful here!

In [38]:
# Loading the players DataFrame
players = pd.read_csv("People.csv")

players.head(3)

,ID,playerID,birthYear,birthMonth,birthDay,birthCity,birthCountry,birthState,deathYear,deathMonth,...,nameLast,nameGiven,weight,height,bats,throws,debut,bbrefID,finalGame,retroID
0,1,aardsda01,1981.0,12.0,27.0,Denver,USA,CO,NaN,NaN,...,Aardsma,David Allan,215.0,75.0,R,R,2004-04-06,aardsda01,2015-08-23,aardd001
1,2,aaronha01,1934.0,2.0,5.0,Mobile,USA,AL,2021.0,1.0,...,Aaron,Henry Louis,180.0,72.0,R,R,1954-04-13,aaronha01,1976-10-03,aaroh101
2,3,aaronto01,1939.0,8.0,5.0,Mobile,USA,AL,1984.0,8.0,...,Aaron,Tommie Lee,190.0,75.0,R,R,1962-04-10,aaronto01,1971-09-26,aarot101

In [39]:
# Join/merge the batting and the players DataFrames

batting2 = batting.merge(players)

batting2.head(3)

,playerID,yearID,stint,teamID,lgID,G,G_batting,AB,R,H,...,nameLast,nameGiven,weight,height,bats,throws,debut,bbrefID,finalGame,retroID
0,aardsda01,2004,1,SFN,NL,11,NaN,0,0,0,...,Aardsma,David Allan,215.0,75.0,R,R,2004-04-06,aardsda01,2015-08-23,aardd001
1,aardsda01,2006,1,CHN,NL,45,NaN,2,0,0,...,Aardsma,David Allan,215.0,75.0,R,R,2004-04-06,aardsda01,2015-08-23,aardd001
2,aardsda01,2007,1,CHA,AL,25,NaN,0,0,0,...,Aardsma,David Allan,215.0,75.0,R,R,2004-04-06,aardsda01,2015-08-23,aardd001

# 3. Assessing which statistics are "good"

As discussed in class, using percentiles is one way to assess what value is impressive for a particular statistic. Let's explore calculating percentiles (and the related concepts of a 5 number summary and boxplot) in Python.


## 3.1 Percentiles

Recall that the $p^{th}$ percentile is the value of a quantitative variable which is greater than *p* percent of the data. We can get the value the $p^{th}$ percentile from a pandas Series using `.percentile()` method. For example, we can get the 80th percentile value using: `my_df["col"].percentile(80)`

**Question 3.1**: What is the 90th percentile value for home runs hit? Does this value seem reasonable to assess what a good player is today? 

To answer these questions, use the batting table that was created in question 2.4. Hint: first get a table that only has home runs and then get use the `percentile()` method.

In [40]:
# Get the 90th percentile of homeruns

## 3.2 Percentiles using only players since the year 2000

One reason that using percentiles on the batting table might not be a good way to find what is a "good" statistic value for the number of home runs is due to the fact that perhaps the game of baseball has changed over time. Let's explore this by finding the percentile value for only players who played since the year 2000.

**Question 3.2:**  What is the 90th percentile value for home runs since 2000? Is it much different than compared to using all years going back to 1871? 

Hint: using Boolean indexing (or the `.query()` method to filtering the data will be useful.

In [41]:
# filter only players who have played since 2000 and see what the 90th percentile value for home runs is

## 3.3 Percentiles using only players that have 502 or more at-bats

Another possible reason this method might not be finding a "good" statistic value for the number of home runs is due to the fact that many players only play a few games in a season and thus do not have that many opportunities to hit home runs. Indeed, to qualify as a leader in a batting statistic, you need to have at least 502 at-bats. Let's explore this possibility by finding the percentile value for only players who had at least 502 at-bats. 

**Question 3.3:**  What is the 90th percentile value for players who had at least 502 at-bats in a season? Is it much different compared to using all players in the Lahman Batting file?

## 3.4 Five number summary

Recall that the five number summary consists of: 
1. The minimum value
2. The 25th percentile value (Q1)
3. The 50th percentile value (the median)
4. The 75th percentiel value (Q3) 
5. The maximum value

**Question 3.4:** What is the 5 number summary when using data from all players and when using data from only players with 502 or more at-bats? Be sure to print out the Python code that calculates these results below. Hint: the `np.min()` and `np.max()` functions will be useful here too.

## 3.5 Boxplots 

Boxplots are a visualization of the five-number summary. We can create boxplots using the Matplotlib library's `plt.boxplot()` function and passing the function a sequence of numbers (e.g., an list, ndarray, or Series of numbers). 

**Question 3.5:** Create a boxplot for home runs using only data for players that have 502 or more at-bats. Based on this boxplot, would the 34 home runs George Springer hit in 2017 be considered an outlier?

In [42]:
import matplotlib.pyplot as plt

# this code makes it so that figures appear in Jupyter notebooks, do not remove it!
%matplotlib inline

## 3.6 Histograms

Histograms are a convenient way to view the full shape of a distribution. We can create a histogram using Matplotlib's `plt.hist()` function, where we pass the function a sequence of numeric data we want to plot as a histogram. 

**Question 3.6:** Create a histogram of the home runs hit by players who have 502 or more at-bats in a season. 

Bonus: see if you can figure out how to create bins in the histogram such that the first bin has the number of players who hit 0 home runs, the second bin has the number of players who hit 1 home run, etc. and the y-axis displays the counts of the number of home runs.

In [43]:
%%capture

# You can run this code to covert this Jupyter notebook into a pdf
!quarto render class_03_answers.ipynb --cache-refresh --to pdf